### ISSUE TITLE
Unable to open input file freetype.lib.

### ISSUE THREAD

**Issue by cryspawner** [singhhdev/CS2-Internal-SkinChanger-Inventory-Changer#3]
Unable to open input file freetype.lib.

**Comment by cryspawner** [comment]
![image](https://github.com/singhhdev/CS2-Internal-SkinChanger-Inventory-Changer/assets/160345870/8a5dcb3d-5811-41ca-a0da-ef3cd4eb9a42)

**Comment by singhhdev** [comment]
can you build in release mode and not debug mode?

**Comment by cryspawner** [comment]
I'm doing it in debug mode. If I release it, it gives a freetype error.

**Comment by singhhdev** [comment]
extract the "extractme.rar"
