### ISSUE TITLE
how to use this 

### ISSUE THREAD

**Issue by swmonoku** [singhhdev/CS2-Internal-SkinChanger-Inventory-Changer#5]
when press "INS", its only "Dump" and "unload" , when i click "Dump", it just crash games. what's matter?

**Comment by singhhdev** [comment]
you have to serach the gun you want to change, then find the skin you want to use, then press dump the skin. if you just press dump it will attempt to dump EVERY single skin in the game.

**Comment by swmonoku** [comment]
> you have to serach the gun you want to change, then find the skin you want to use, then press dump the skin. if you just press dump it will attempt to dump EVERY single skin in the game.
search the gun in game or in the code ?
