### ISSUE TITLE
Hand grenade, flash, combustion bottle

### ISSUE THREAD

**Issue by jackKiZhu** [singhhdev/CS2-Internal-SkinChanger-Inventory-Changer#9]
There are issues with the grenade, flash, and combustion bottle models

**Comment by singhhdev** [comment]
follow this:
if (!pWeaponSceneNode) continue;
int id = pAttributeContainer->m_Item()->m_iItemDefinitionIndex();
if (id == 43 || id == 44 || id == 45 || id == 46 ||id == 47 || id == 48 || id == 49 ) continue;


just copy and paste this after the if (!pWeaponSceneNode) continue;

(this really ghetto, but gets the job done)

should fix the issue for you!
